---
- name: Report generation
  hosts: all
  vars:
    - temp: temp
    - results: results 
  tasks:
    - include_vars: "{{temp}}/{{inventory_hostname}}.yml"
    - file: path="{{results}}" state=absent
      run_once: true
    - file: path="{{results}}" state=directory
      run_once: true
    - file: path="{{results}}/report.txt" state=touch
      run_once: true
    - template: src="tp-report.j2" dest="{{results}}/report.txt"
      vars:
        allhosts: "{{hostvars}}"
      run_once: true